/**
 * Payment receipt generator — Web version.
 * Opens receipt HTML in a new window for printing.
 */

export interface ReceiptData {
  receiptNumber: string;
  tenantName: string;
  propertyName: string;
  unitNumber: string;
  amount: number;
  paymentDate: string;
  monthYear: string;
  lang: "en" | "ar";
}

function generateReceiptHTML(data: ReceiptData): string {
  const isAr = data.lang === "ar";
  const dir = isAr ? "rtl" : "ltr";
  const currency = isAr ? "ريال" : "SAR";
  const formattedAmount = `${data.amount.toLocaleString()} ${currency}`;

  const labels = {
    title: isAr ? "إيصال دفع" : "Payment Receipt",
    receiptNo: isAr ? "رقم الإيصال" : "Receipt No",
    date: isAr ? "التاريخ" : "Date",
    tenant: isAr ? "المستأجر" : "Tenant",
    property: isAr ? "العقار" : "Property",
    unit: isAr ? "الوحدة" : "Unit",
    amount: isAr ? "المبلغ" : "Amount",
    period: isAr ? "الفترة" : "Period",
    thankYou: isAr ? "شكراً لك" : "Thank you for your payment",
    appName: isAr ? "أملاكي" : "Amlakey",
    powered: isAr ? "تم الإنشاء بواسطة أملاكي" : "Generated by Amlakey",
  };

  return `
<!DOCTYPE html>
<html dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title} - ${data.receiptNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #F8FAFC;
      padding: 40px 30px;
      direction: ${dir};
      color: #1E293B;
    }
    .receipt {
      max-width: 500px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      padding: 32px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.08);
    }
    .header {
      text-align: center;
      margin-bottom: 24px;
      padding-bottom: 20px;
      border-bottom: 2px solid #E2E8F0;
    }
    .logo { font-size: 28px; font-weight: 800; color: #0284C7; margin-bottom: 4px; }
    .title { font-size: 18px; color: #64748B; font-weight: 500; }
    .receipt-no {
      text-align: center;
      background: #F1F5F9;
      padding: 8px 16px;
      border-radius: 8px;
      font-size: 13px;
      color: #64748B;
      margin-bottom: 20px;
    }
    .amount-box {
      text-align: center;
      background: linear-gradient(135deg, #0284C7, #0EA5E9);
      color: white;
      padding: 20px;
      border-radius: 12px;
      margin-bottom: 24px;
    }
    .amount-label { font-size: 13px; opacity: 0.85; margin-bottom: 4px; }
    .amount-value { font-size: 32px; font-weight: 800; }
    .details { margin-bottom: 24px; }
    .row {
      display: flex;
      justify-content: space-between;
      padding: 10px 0;
      border-bottom: 1px solid #F1F5F9;
    }
    .row:last-child { border-bottom: none; }
    .label { color: #94A3B8; font-size: 14px; }
    .value { font-weight: 600; font-size: 14px; text-align: ${isAr ? "left" : "right"}; }
    .footer {
      text-align: center;
      padding-top: 20px;
      border-top: 2px solid #E2E8F0;
    }
    .thank-you { color: #10B981; font-weight: 600; font-size: 16px; margin-bottom: 8px; }
    .powered { color: #CBD5E1; font-size: 11px; }
    @media print {
      body { padding: 0; background: white; }
      .receipt { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="header">
      <div class="logo">${labels.appName}</div>
      <div class="title">${labels.title}</div>
    </div>
    <div class="receipt-no">${labels.receiptNo}: ${data.receiptNumber}</div>
    <div class="amount-box">
      <div class="amount-label">${labels.amount}</div>
      <div class="amount-value">${formattedAmount}</div>
    </div>
    <div class="details">
      <div class="row">
        <span class="label">${labels.tenant}</span>
        <span class="value">${data.tenantName}</span>
      </div>
      <div class="row">
        <span class="label">${labels.property}</span>
        <span class="value">${data.propertyName}</span>
      </div>
      <div class="row">
        <span class="label">${labels.unit}</span>
        <span class="value">${data.unitNumber}</span>
      </div>
      <div class="row">
        <span class="label">${labels.date}</span>
        <span class="value">${data.paymentDate}</span>
      </div>
      <div class="row">
        <span class="label">${labels.period}</span>
        <span class="value">${data.monthYear}</span>
      </div>
    </div>
    <div class="footer">
      <div class="thank-you">✅ ${labels.thankYou}</div>
      <div class="powered">${labels.powered}</div>
    </div>
  </div>
</body>
</html>`;
}

/** Generate receipt HTML and open in a new window for printing */
export async function generateAndShareReceipt(data: ReceiptData): Promise<void> {
  const html = generateReceiptHTML(data);
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    // Small delay to ensure content is rendered before print dialog
    setTimeout(() => printWindow.print(), 500);
  }
}
