/**
 * Payment receipt PDF generator.
 * Uses expo-print to generate HTML → PDF, and expo-sharing to share.
 */
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export interface ReceiptData {
  receiptNumber: string;
  tenantName: string;
  propertyName: string;
  unitNumber: string;
  amount: number;
  paymentDate: string;
  monthYear: string;
  lang: "en" | "ar";
  ownerName?: string;
  city?: string;
}

/** Generate a receipt number in format RCP-{YYYY}-{random 4 chars} */
export function generateReceiptNumber(): string {
  const year = new Date().getFullYear();
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let rand = "";
  for (let i = 0; i < 4; i++) rand += chars[Math.floor(Math.random() * chars.length)];
  return `RCP-${year}-${rand}`;
}

function formatAmountWithCommas(amount: number): string {
  return amount.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 2 });
}

function generateReceiptHTML(data: ReceiptData): string {
  const isAr = data.lang === "ar";
  const dir = isAr ? "rtl" : "ltr";
  const align = isAr ? "right" : "left";
  const currency = isAr ? "ريال" : "SAR";
  const formattedAmount = `${formatAmountWithCommas(data.amount)} ${currency}`;
  const issuedDate = new Date().toLocaleDateString(isAr ? "ar-SA" : "en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  const labels = {
    title: isAr ? "إيصال دفع" : "Payment Receipt",
    receiptNo: isAr ? "رقم الإيصال" : "Receipt No",
    date: isAr ? "التاريخ" : "Date",
    tenant: isAr ? "المستأجر" : "Tenant",
    property: isAr ? "العقار" : "Property",
    unit: isAr ? "الوحدة" : "Unit",
    amount: isAr ? "المبلغ" : "Amount",
    period: isAr ? "الفترة" : "Period",
    city: isAr ? "المدينة" : "City",
    owner: isAr ? "المالك" : "Owner",
    thankYou: isAr ? "شكراً لك" : "Thank you for your payment",
    appName: isAr ? "أملاكي" : "Amlakey",
    powered: isAr ? "تم الإنشاء بواسطة أملاكي" : "Generated by Amlakey",
    issuedOn: isAr ? "صدر بتاريخ" : "Issued on",
  };

  const ownerLine = data.ownerName
    ? `<div class="owner-name">${labels.owner}: ${data.ownerName}</div>`
    : "";

  const cityRow = data.city
    ? `<div class="row">
        <span class="label">${labels.city}</span>
        <span class="value">${data.city}</span>
      </div>`
    : "";

  return `
<!DOCTYPE html>
<html dir="${dir}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #F8FAFC;
      padding: 40px 30px;
      direction: ${dir};
      color: #1E293B;
    }
    .receipt {
      max-width: 500px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      padding: 0;
      box-shadow: 0 4px 12px rgba(0,0,0,0.08);
      overflow: hidden;
      position: relative;
    }
    /* Watermark background pattern */
    .receipt::before {
      content: "";
      position: absolute;
      top: 0; left: 0; right: 0; bottom: 0;
      background-image:
        radial-gradient(circle at 20% 80%, rgba(2,132,199,0.03) 0%, transparent 50%),
        radial-gradient(circle at 80% 20%, rgba(14,165,233,0.03) 0%, transparent 50%),
        repeating-linear-gradient(
          45deg,
          transparent,
          transparent 40px,
          rgba(2,132,199,0.015) 40px,
          rgba(2,132,199,0.015) 41px
        );
      pointer-events: none;
      z-index: 0;
    }
    /* Gradient top bar */
    .top-bar {
      height: 6px;
      background: linear-gradient(90deg, #0284C7, #0EA5E9, #38BDF8, #0EA5E9, #0284C7);
    }
    .receipt-content {
      padding: 32px;
      position: relative;
      z-index: 1;
    }
    .header {
      text-align: center;
      margin-bottom: 24px;
      padding-bottom: 20px;
      border-bottom: 2px solid #E2E8F0;
    }
    .logo { font-size: 28px; font-weight: 800; color: #0284C7; margin-bottom: 4px; }
    .owner-name { font-size: 14px; color: #475569; font-weight: 500; margin-top: 2px; }
    .title { font-size: 18px; color: #64748B; font-weight: 500; margin-top: 6px; }
    .receipt-no {
      text-align: center;
      background: #F1F5F9;
      padding: 8px 16px;
      border-radius: 8px;
      font-size: 13px;
      color: #64748B;
      margin-bottom: 20px;
      letter-spacing: 0.5px;
    }
    .amount-box {
      text-align: center;
      background: linear-gradient(135deg, #0284C7, #0EA5E9);
      color: white;
      padding: 24px 20px;
      border-radius: 12px;
      margin-bottom: 24px;
    }
    .amount-label { font-size: 13px; opacity: 0.85; margin-bottom: 6px; }
    .amount-value { font-size: 36px; font-weight: 800; letter-spacing: 1px; }
    .amount-currency { font-size: 16px; font-weight: 500; opacity: 0.9; margin-top: 4px; }
    .details { margin-bottom: 24px; }
    .row {
      display: flex;
      justify-content: space-between;
      padding: 12px 0;
      border-bottom: 1px solid #F1F5F9;
    }
    .row:last-child { border-bottom: none; }
    .label { color: #94A3B8; font-size: 14px; }
    .value { font-weight: 600; font-size: 14px; text-align: ${isAr ? "left" : "right"}; }
    .footer {
      text-align: center;
      padding-top: 20px;
      border-top: 2px solid #E2E8F0;
    }
    .thank-you { color: #10B981; font-weight: 600; font-size: 16px; margin-bottom: 10px; }
    .issued-date { color: #94A3B8; font-size: 12px; margin-bottom: 6px; }
    .powered { color: #CBD5E1; font-size: 11px; }
  </style>
</head>
<body>
  <div class="receipt">
    <div class="top-bar"></div>
    <div class="receipt-content">
      <div class="header">
        <div class="logo">${labels.appName}</div>
        ${ownerLine}
        <div class="title">${labels.title}</div>
      </div>
      <div class="receipt-no">${labels.receiptNo}: ${data.receiptNumber}</div>
      <div class="amount-box">
        <div class="amount-label">${labels.amount}</div>
        <div class="amount-value">${formatAmountWithCommas(data.amount)}</div>
        <div class="amount-currency">${currency}</div>
      </div>
      <div class="details">
        <div class="row">
          <span class="label">${labels.tenant}</span>
          <span class="value">${data.tenantName}</span>
        </div>
        <div class="row">
          <span class="label">${labels.property}</span>
          <span class="value">${data.propertyName}</span>
        </div>
        ${cityRow}
        <div class="row">
          <span class="label">${labels.unit}</span>
          <span class="value">${data.unitNumber}</span>
        </div>
        <div class="row">
          <span class="label">${labels.date}</span>
          <span class="value">${data.paymentDate}</span>
        </div>
        <div class="row">
          <span class="label">${labels.period}</span>
          <span class="value">${data.monthYear}</span>
        </div>
      </div>
      <div class="footer">
        <div class="thank-you">${labels.thankYou}</div>
        <div class="issued-date">${labels.issuedOn}: ${issuedDate}</div>
        <div class="powered">${labels.powered}</div>
      </div>
    </div>
  </div>
</body>
</html>`;
}

/** Generate a PDF receipt and share it via the native share sheet */
export async function generateAndShareReceipt(data: ReceiptData): Promise<void> {
  const html = generateReceiptHTML(data);
  const { uri } = await Print.printToFileAsync({ html, width: 612, height: 792 });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: data.lang === "ar" ? "مشاركة الإيصال" : "Share Receipt",
      UTI: "com.adobe.pdf",
    });
  }
}
